apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: webapi
  namespace: dsd-test-project
  labels:
    app: webapi
spec:
  source:
    type: Git
    git:
      uri: https://github.com/light-weaver/dockertests
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: webapi.Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: webapi:latest
