apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: webapiInit
  namespace: dsd-test-project
  labels:
    app: webapiInit
spec:
  source:
    type: Git
    git:
      uri: https://github.com/light-weaver/dockertests
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: initAndCron.Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: webapiinit:latest
